### ISSUE TITLE
iOS crash when receiving remote feed

### ISSUE THREAD

**Issue by cbarronmira** [voximplant/unity_sdk#18]
When building from the most recent source, the app crashes immediately after OnCallConnected. I've tested with opengl, and with metal, and get the same result

Crash Log:
2018-04-05 17:43:26.193847-0700 voxdemo[866:224080] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[RTCVideoFrame dataY]: unrecognized selector sent to instance 0x1c464a1a0'
*** First throw call stack:
(0x18543a364 0x184680528 0x185447828 0x18543fd10 0x185324ecc 0x103466da0 0x1034667d4 0x1853e2790 0x1853e2060 0x1853e02c8 0x1852ffe58 0x185d35594 0x103466198 0x185e370f4 0x1850602b4 0x185060180 0x18505eb74)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by niveuseverto** [comment]
Greetings.

This issue is resolved.

Please, update SDK sources and check if everything is working now.
