### ISSUE TITLE
Work with Unity for Windows

### ISSUE THREAD

**Issue by cosmo-naut** [voximplant/unity_sdk#19]
Does it work with Unity for Windows? As opposed to Android/iOS

**Comment by niveuseverto** [comment]
Greetings,

At this moment windows platform isn't supported.

We don't plan to include new platforms in the near future.

**Comment by cosmo-naut** [comment]
For anybody curious

A similar piece of software that supports Windows is Agora.io

https://github.com/AgoraIO/Video-Call-for-Mobile-Gaming/issues/8
